global using LoadBalancingClient_Internal = ObjectPublicIPhotonPeerListenerObStNuStOb1CoObBoDiUnique;
global using PhotonNetwork_Internal = ObjectPublicAbstractSealedObInObStInCo2ObInBoUnique;
global using RaiseEventOptions_Internal = ObjectPublicObByObInByObObUnique;
global using Player_Internal = MonoBehaviourPublicAPOb_vOb_l_pBoOb_UBoUnique;
global using VRCPlayer_Internal = MonoBehaviour1PublicOb_pOb_s_pBoGaOb_pStUnique;
global using PlayerNet_Internal = MonoBehaviour1PublicOb_vInByInBoObBySiObUnique;
global using UdonSync_Internal = MonoBehaviour1PrivateBoUdOb1DiObBo2InObUnique;
global using RoomManager_Internal = MonoBehaviourPublicBoApSiApBoObStApBo1Unique;